### ISSUE TITLE
simulation stack gets merged with old stack

### ISSUE THREAD

**Issue by KillariDev** [DarkFlorist/bouquet#50]
1) create simulation stack of 2 transactions
2) import transactions to bouquet
3) delete simulation stack and have a stack of one transaction (in interceptor)
4) import transactions to bouquet
5) bouquet switches the first transaction from the simulation stack but the second transaction still remains in bouquet even thought it does not exist in the simulation stack anymore

**Comment by KillariDev** [comment]
this also throws following error to console:
```ts
Configure.tsx:101 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'input')
    at Configure.tsx:101:43
    at Array.map (<anonymous>)
    at _.Configure [as constructor] (Configure.tsx:96:35)
    at _.O [as render] (index.js:532:14)
    at j (index.js:190:14)
    at w (children.js:137:3)
    at j (index.js:212:4)
    at w (children.js:137:3)
    at L (index.js:418:4)
    at j (index.js:246:20)
(anonymous)	@	Configure.tsx:101
Configure	@	Configure.tsx:96
O	@	index.js:532
j	@	index.js:190
w	@	children.js:137
j	@	index.js:212
w	@	children.js:137
L	@	index.js:418
j	@	index.js:246
w	@	children.js:137
L	@	index.js:418
j	@	index.js:246
w	@	children.js:137
L	@	index.js:418
j	@	index.js:246
w	@	children.js:137
j	@	index.js:212
(anonymous)	@	component.js:130
g	@	component.js:220
Promise.then (async)		
m	@	component.js:208
_.setState	@	component.js:51
i.c	@	index.ts:149
t	@	index.ts:63
set	@	index.ts:321
importFromInterceptor	@	Import.tsx:58
await in importFromInterceptor (async)		
onClick	@	Import.tsx:98
I	@	props.js:153
```

**Comment by 0xjimmy** [comment]
Looks like the Configure Component doesn't clear the list of addresses /w pk inputs needed
